version: "3"
services:
  app:
    container_name: golangapp
    build: .
    volumes:
      - ./app:/go/src/app
      - ./build:/go/bin
    command: "sh -c 'go get github.com/gorilla/mux'"
    ports:
      - 3000:3000
    links:
      - postgres
      - redis
  postgres:
    image: postgres:9.6
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=golangapp-dev
      - PGDATA=/data/db
    ports:
      - 5432:5432
    # volumes:
    #   - ./dbdata:/data/db
  redis:
    image: redis:3
